version: 2

registries:
  labymod-maven:
    type: maven-repository
    url: https://dist.labymod.net/api/v1/maven/release/

  neoforged-maven:
    type: maven-repository
    url: https://maven.neoforged.net/releases/

  fabricmc-maven:
    type: maven-repository
    url: https://maven.fabricmc.net/

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /
    registries: '*'
    schedule:
      interval: weekly
